### ISSUE TITLE
osascript (Not Responding)

### ISSUE THREAD

**Issue by przemyslawpluta** [FWeinb/node-osascript#4]
Is there an options for script timeout? At the moment if this state occurs - osascript (Not Responding) visible in the Activity Monitor there is no response or error emitted back?

**Comment by FWeinb** [comment]
I would welcome this feature too. Not much time but would review a PR for this.

**Comment by seblavoie** [comment]
I would love if this could be an option. I am not sure how to implement this, but if you have some general directions to give me explaining where I should look at to get going, I'd love to help you with this.

**Comment by seblavoie** [comment]
You can get a part of the solution by modifying the Applescript timeout value which will throw an `Apple Event Timed Out` error in the package. Seems like the default is 2 minutes. You can  change it which this code:

```
with timeout of (30 * 60) seconds
   tell application "Finder"
       duplicate alias "path:to:really BIG folder:"
       set name of result to "duplicate gotta hey!"
   end tell
end timeout
```

More information here: http://macscripter.net/viewtopic.php?id=24461

**Comment by AckerApple** [comment]
I have made a pull request that allow node to kill the AppleScript.

Pull Request #4

**Comment by AckerApple** [comment]
My pull request has been accepted and merged. You could close this issue now.

How to timeout is in the readme docs
